version: '3'

services:
  kafkaconsumer:
    build: .
    volumes:
      - ./keys:/home/keys
      - ./train:/home/train
      - ./faces:/home/faces

  facerecognition:
    image: machinebox/facebox
    ports:
      - 8080:8080
    environment:
      - MB_KEY=MB_KEY