# docker build . -t face-recognition
# docker run --volume=$(pwd)/app:/app -it face-recognition

FROM python:3.7-alpine

# COPY requirements.txt /opt/pandas/build/requirements.txt

# RUN pip install -r /opt/pandas/build/requirements.txt

# ADD /etl /etl

CMD ["python"]
